---
title: "从数据到论文"
author: "姓名"
date: "`r Sys.Date()`"
output: 
  officedown::rdocx_document:
    number_sections: yes
    df_print: kable
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo         = FALSE,
  warning      = FALSE,
  message      = FALSE,
  fig.width    = 6,
  fig.asp      = 0.618,
  dpi          = 600
)
options(digits = 3)
```


# 数据

```{r}
library(tidyverse)

data <- readxl::read_excel("./data/cleandata.xlsx")

data %>% 
  head(6) %>% 
  select(respondent, bususefrequency, age, gender) %>% 
  flextable::flextable() %>% 
  flextable::autofit()
```


# 可视化探索

画出公交车使用频率的分布图

```{r}
data %>% 
  count(bususefrequency) %>% 
  
  
  ggplot(aes(x = bususefrequency, y = n)) +
  geom_col()
```


# 美化

```{r}
data %>% 
  count(bususefrequency) %>% 
  mutate(
    bususefrequency = factor(bususefrequency,
      levels = c(1, 2, 3, 4),
      labels = c(
        "< 5 times",
        "  6–10 times",
        "  11–15 times",
        "> 15 times"
      )
    )
  ) %>% 
  ggplot(aes(x = bususefrequency, y = n)) +
  geom_col(fill = "orange") +
  geom_text(aes(label = n), vjust = -0.5) +
  scale_y_continuous(limits = c(0, 130), breaks = seq(0, 130, by = 25)) +
  labs(x = NULL, y = NULL, title = "Frequency of bus use") +
  theme_classic()
```

